// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: player.proto

package top.liubowen.proto;

public final class PlayerProto {
  private PlayerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   ** 玩家状态信息 
   * </pre>
   *
   * Protobuf enum {@code playerProto.PlayerState}
   */
  public enum PlayerState
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *  在线
     * </pre>
     *
     * <code>ONLINE = 0;</code>
     */
    ONLINE(0),
    /**
     * <pre>
     *  离线
     * </pre>
     *
     * <code>OFFLINE = 1;</code>
     */
    OFFLINE(1),
    /**
     * <pre>
     *  游戏中
     * </pre>
     *
     * <code>IN_GAME = 2;</code>
     */
    IN_GAME(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *  在线
     * </pre>
     *
     * <code>ONLINE = 0;</code>
     */
    public static final int ONLINE_VALUE = 0;
    /**
     * <pre>
     *  离线
     * </pre>
     *
     * <code>OFFLINE = 1;</code>
     */
    public static final int OFFLINE_VALUE = 1;
    /**
     * <pre>
     *  游戏中
     * </pre>
     *
     * <code>IN_GAME = 2;</code>
     */
    public static final int IN_GAME_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PlayerState valueOf(int value) {
      return forNumber(value);
    }

    public static PlayerState forNumber(int value) {
      switch (value) {
        case 0: return ONLINE;
        case 1: return OFFLINE;
        case 2: return IN_GAME;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PlayerState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PlayerState> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PlayerState>() {
            public PlayerState findValueByNumber(int number) {
              return PlayerState.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return top.liubowen.proto.PlayerProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final PlayerState[] VALUES = values();

    public static PlayerState valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PlayerState(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:playerProto.PlayerState)
  }

  public interface SimplePlayerMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:playerProto.SimplePlayerMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *  玩家id
     * </pre>
     *
     * <code>int64 player_id = 1;</code>
     */
    long getPlayerId();

    /**
     * <pre>
     *  玩家昵称
     * </pre>
     *
     * <code>string nickname = 2;</code>
     */
    java.lang.String getNickname();
    /**
     * <pre>
     *  玩家昵称
     * </pre>
     *
     * <code>string nickname = 2;</code>
     */
    com.google.protobuf.ByteString
        getNicknameBytes();

    /**
     * <pre>
     *  玩家头像
     * </pre>
     *
     * <code>string head_image = 3;</code>
     */
    java.lang.String getHeadImage();
    /**
     * <pre>
     *  玩家头像
     * </pre>
     *
     * <code>string head_image = 3;</code>
     */
    com.google.protobuf.ByteString
        getHeadImageBytes();

    /**
     * <pre>
     *  玩家状态
     * </pre>
     *
     * <code>.playerProto.PlayerState state = 4;</code>
     */
    int getStateValue();
    /**
     * <pre>
     *  玩家状态
     * </pre>
     *
     * <code>.playerProto.PlayerState state = 4;</code>
     */
    top.liubowen.proto.PlayerProto.PlayerState getState();
  }
  /**
   * <pre>
   ** 基础玩家信息 
   * </pre>
   *
   * Protobuf type {@code playerProto.SimplePlayerMsg}
   */
  public  static final class SimplePlayerMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:playerProto.SimplePlayerMsg)
      SimplePlayerMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SimplePlayerMsg.newBuilder() to construct.
    private SimplePlayerMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SimplePlayerMsg() {
      playerId_ = 0L;
      nickname_ = "";
      headImage_ = "";
      state_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SimplePlayerMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              playerId_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              nickname_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              headImage_ = s;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              state_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return top.liubowen.proto.PlayerProto.internal_static_playerProto_SimplePlayerMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return top.liubowen.proto.PlayerProto.internal_static_playerProto_SimplePlayerMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              top.liubowen.proto.PlayerProto.SimplePlayerMsg.class, top.liubowen.proto.PlayerProto.SimplePlayerMsg.Builder.class);
    }

    public static final int PLAYER_ID_FIELD_NUMBER = 1;
    private long playerId_;
    /**
     * <pre>
     *  玩家id
     * </pre>
     *
     * <code>int64 player_id = 1;</code>
     */
    public long getPlayerId() {
      return playerId_;
    }

    public static final int NICKNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object nickname_;
    /**
     * <pre>
     *  玩家昵称
     * </pre>
     *
     * <code>string nickname = 2;</code>
     */
    public java.lang.String getNickname() {
      java.lang.Object ref = nickname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nickname_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *  玩家昵称
     * </pre>
     *
     * <code>string nickname = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNicknameBytes() {
      java.lang.Object ref = nickname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HEAD_IMAGE_FIELD_NUMBER = 3;
    private volatile java.lang.Object headImage_;
    /**
     * <pre>
     *  玩家头像
     * </pre>
     *
     * <code>string head_image = 3;</code>
     */
    public java.lang.String getHeadImage() {
      java.lang.Object ref = headImage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        headImage_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *  玩家头像
     * </pre>
     *
     * <code>string head_image = 3;</code>
     */
    public com.google.protobuf.ByteString
        getHeadImageBytes() {
      java.lang.Object ref = headImage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        headImage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATE_FIELD_NUMBER = 4;
    private int state_;
    /**
     * <pre>
     *  玩家状态
     * </pre>
     *
     * <code>.playerProto.PlayerState state = 4;</code>
     */
    public int getStateValue() {
      return state_;
    }
    /**
     * <pre>
     *  玩家状态
     * </pre>
     *
     * <code>.playerProto.PlayerState state = 4;</code>
     */
    public top.liubowen.proto.PlayerProto.PlayerState getState() {
      top.liubowen.proto.PlayerProto.PlayerState result = top.liubowen.proto.PlayerProto.PlayerState.valueOf(state_);
      return result == null ? top.liubowen.proto.PlayerProto.PlayerState.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (playerId_ != 0L) {
        output.writeInt64(1, playerId_);
      }
      if (!getNicknameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nickname_);
      }
      if (!getHeadImageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, headImage_);
      }
      if (state_ != top.liubowen.proto.PlayerProto.PlayerState.ONLINE.getNumber()) {
        output.writeEnum(4, state_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (playerId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, playerId_);
      }
      if (!getNicknameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nickname_);
      }
      if (!getHeadImageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, headImage_);
      }
      if (state_ != top.liubowen.proto.PlayerProto.PlayerState.ONLINE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, state_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof top.liubowen.proto.PlayerProto.SimplePlayerMsg)) {
        return super.equals(obj);
      }
      top.liubowen.proto.PlayerProto.SimplePlayerMsg other = (top.liubowen.proto.PlayerProto.SimplePlayerMsg) obj;

      boolean result = true;
      result = result && (getPlayerId()
          == other.getPlayerId());
      result = result && getNickname()
          .equals(other.getNickname());
      result = result && getHeadImage()
          .equals(other.getHeadImage());
      result = result && state_ == other.state_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PLAYER_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPlayerId());
      hash = (37 * hash) + NICKNAME_FIELD_NUMBER;
      hash = (53 * hash) + getNickname().hashCode();
      hash = (37 * hash) + HEAD_IMAGE_FIELD_NUMBER;
      hash = (53 * hash) + getHeadImage().hashCode();
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + state_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static top.liubowen.proto.PlayerProto.SimplePlayerMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.liubowen.proto.PlayerProto.SimplePlayerMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.liubowen.proto.PlayerProto.SimplePlayerMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.liubowen.proto.PlayerProto.SimplePlayerMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.liubowen.proto.PlayerProto.SimplePlayerMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.liubowen.proto.PlayerProto.SimplePlayerMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.liubowen.proto.PlayerProto.SimplePlayerMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.liubowen.proto.PlayerProto.SimplePlayerMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static top.liubowen.proto.PlayerProto.SimplePlayerMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static top.liubowen.proto.PlayerProto.SimplePlayerMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static top.liubowen.proto.PlayerProto.SimplePlayerMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.liubowen.proto.PlayerProto.SimplePlayerMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(top.liubowen.proto.PlayerProto.SimplePlayerMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     ** 基础玩家信息 
     * </pre>
     *
     * Protobuf type {@code playerProto.SimplePlayerMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:playerProto.SimplePlayerMsg)
        top.liubowen.proto.PlayerProto.SimplePlayerMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return top.liubowen.proto.PlayerProto.internal_static_playerProto_SimplePlayerMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return top.liubowen.proto.PlayerProto.internal_static_playerProto_SimplePlayerMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                top.liubowen.proto.PlayerProto.SimplePlayerMsg.class, top.liubowen.proto.PlayerProto.SimplePlayerMsg.Builder.class);
      }

      // Construct using top.liubowen.proto.PlayerProto.SimplePlayerMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        playerId_ = 0L;

        nickname_ = "";

        headImage_ = "";

        state_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return top.liubowen.proto.PlayerProto.internal_static_playerProto_SimplePlayerMsg_descriptor;
      }

      public top.liubowen.proto.PlayerProto.SimplePlayerMsg getDefaultInstanceForType() {
        return top.liubowen.proto.PlayerProto.SimplePlayerMsg.getDefaultInstance();
      }

      public top.liubowen.proto.PlayerProto.SimplePlayerMsg build() {
        top.liubowen.proto.PlayerProto.SimplePlayerMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public top.liubowen.proto.PlayerProto.SimplePlayerMsg buildPartial() {
        top.liubowen.proto.PlayerProto.SimplePlayerMsg result = new top.liubowen.proto.PlayerProto.SimplePlayerMsg(this);
        result.playerId_ = playerId_;
        result.nickname_ = nickname_;
        result.headImage_ = headImage_;
        result.state_ = state_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof top.liubowen.proto.PlayerProto.SimplePlayerMsg) {
          return mergeFrom((top.liubowen.proto.PlayerProto.SimplePlayerMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(top.liubowen.proto.PlayerProto.SimplePlayerMsg other) {
        if (other == top.liubowen.proto.PlayerProto.SimplePlayerMsg.getDefaultInstance()) return this;
        if (other.getPlayerId() != 0L) {
          setPlayerId(other.getPlayerId());
        }
        if (!other.getNickname().isEmpty()) {
          nickname_ = other.nickname_;
          onChanged();
        }
        if (!other.getHeadImage().isEmpty()) {
          headImage_ = other.headImage_;
          onChanged();
        }
        if (other.state_ != 0) {
          setStateValue(other.getStateValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        top.liubowen.proto.PlayerProto.SimplePlayerMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (top.liubowen.proto.PlayerProto.SimplePlayerMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long playerId_ ;
      /**
       * <pre>
       *  玩家id
       * </pre>
       *
       * <code>int64 player_id = 1;</code>
       */
      public long getPlayerId() {
        return playerId_;
      }
      /**
       * <pre>
       *  玩家id
       * </pre>
       *
       * <code>int64 player_id = 1;</code>
       */
      public Builder setPlayerId(long value) {
        
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  玩家id
       * </pre>
       *
       * <code>int64 player_id = 1;</code>
       */
      public Builder clearPlayerId() {
        
        playerId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object nickname_ = "";
      /**
       * <pre>
       *  玩家昵称
       * </pre>
       *
       * <code>string nickname = 2;</code>
       */
      public java.lang.String getNickname() {
        java.lang.Object ref = nickname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nickname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *  玩家昵称
       * </pre>
       *
       * <code>string nickname = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNicknameBytes() {
        java.lang.Object ref = nickname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nickname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *  玩家昵称
       * </pre>
       *
       * <code>string nickname = 2;</code>
       */
      public Builder setNickname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nickname_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  玩家昵称
       * </pre>
       *
       * <code>string nickname = 2;</code>
       */
      public Builder clearNickname() {
        
        nickname_ = getDefaultInstance().getNickname();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  玩家昵称
       * </pre>
       *
       * <code>string nickname = 2;</code>
       */
      public Builder setNicknameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nickname_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object headImage_ = "";
      /**
       * <pre>
       *  玩家头像
       * </pre>
       *
       * <code>string head_image = 3;</code>
       */
      public java.lang.String getHeadImage() {
        java.lang.Object ref = headImage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          headImage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *  玩家头像
       * </pre>
       *
       * <code>string head_image = 3;</code>
       */
      public com.google.protobuf.ByteString
          getHeadImageBytes() {
        java.lang.Object ref = headImage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          headImage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *  玩家头像
       * </pre>
       *
       * <code>string head_image = 3;</code>
       */
      public Builder setHeadImage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        headImage_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  玩家头像
       * </pre>
       *
       * <code>string head_image = 3;</code>
       */
      public Builder clearHeadImage() {
        
        headImage_ = getDefaultInstance().getHeadImage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  玩家头像
       * </pre>
       *
       * <code>string head_image = 3;</code>
       */
      public Builder setHeadImageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        headImage_ = value;
        onChanged();
        return this;
      }

      private int state_ = 0;
      /**
       * <pre>
       *  玩家状态
       * </pre>
       *
       * <code>.playerProto.PlayerState state = 4;</code>
       */
      public int getStateValue() {
        return state_;
      }
      /**
       * <pre>
       *  玩家状态
       * </pre>
       *
       * <code>.playerProto.PlayerState state = 4;</code>
       */
      public Builder setStateValue(int value) {
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  玩家状态
       * </pre>
       *
       * <code>.playerProto.PlayerState state = 4;</code>
       */
      public top.liubowen.proto.PlayerProto.PlayerState getState() {
        top.liubowen.proto.PlayerProto.PlayerState result = top.liubowen.proto.PlayerProto.PlayerState.valueOf(state_);
        return result == null ? top.liubowen.proto.PlayerProto.PlayerState.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *  玩家状态
       * </pre>
       *
       * <code>.playerProto.PlayerState state = 4;</code>
       */
      public Builder setState(top.liubowen.proto.PlayerProto.PlayerState value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        state_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  玩家状态
       * </pre>
       *
       * <code>.playerProto.PlayerState state = 4;</code>
       */
      public Builder clearState() {
        
        state_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:playerProto.SimplePlayerMsg)
    }

    // @@protoc_insertion_point(class_scope:playerProto.SimplePlayerMsg)
    private static final top.liubowen.proto.PlayerProto.SimplePlayerMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new top.liubowen.proto.PlayerProto.SimplePlayerMsg();
    }

    public static top.liubowen.proto.PlayerProto.SimplePlayerMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SimplePlayerMsg>
        PARSER = new com.google.protobuf.AbstractParser<SimplePlayerMsg>() {
      public SimplePlayerMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SimplePlayerMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SimplePlayerMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SimplePlayerMsg> getParserForType() {
      return PARSER;
    }

    public top.liubowen.proto.PlayerProto.SimplePlayerMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PlayerMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:playerProto.PlayerMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *  玩家基础信息
     * </pre>
     *
     * <code>.playerProto.SimplePlayerMsg simple_player = 1;</code>
     */
    boolean hasSimplePlayer();
    /**
     * <pre>
     *  玩家基础信息
     * </pre>
     *
     * <code>.playerProto.SimplePlayerMsg simple_player = 1;</code>
     */
    top.liubowen.proto.PlayerProto.SimplePlayerMsg getSimplePlayer();
    /**
     * <pre>
     *  玩家基础信息
     * </pre>
     *
     * <code>.playerProto.SimplePlayerMsg simple_player = 1;</code>
     */
    top.liubowen.proto.PlayerProto.SimplePlayerMsgOrBuilder getSimplePlayerOrBuilder();

    /**
     * <pre>
     *  玩家房卡数量
     * </pre>
     *
     * <code>int32 room_card_num = 2;</code>
     */
    int getRoomCardNum();
  }
  /**
   * <pre>
   ** 玩家信息 
   * </pre>
   *
   * Protobuf type {@code playerProto.PlayerMsg}
   */
  public  static final class PlayerMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:playerProto.PlayerMsg)
      PlayerMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PlayerMsg.newBuilder() to construct.
    private PlayerMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlayerMsg() {
      roomCardNum_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              top.liubowen.proto.PlayerProto.SimplePlayerMsg.Builder subBuilder = null;
              if (simplePlayer_ != null) {
                subBuilder = simplePlayer_.toBuilder();
              }
              simplePlayer_ = input.readMessage(top.liubowen.proto.PlayerProto.SimplePlayerMsg.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(simplePlayer_);
                simplePlayer_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              roomCardNum_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return top.liubowen.proto.PlayerProto.internal_static_playerProto_PlayerMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return top.liubowen.proto.PlayerProto.internal_static_playerProto_PlayerMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              top.liubowen.proto.PlayerProto.PlayerMsg.class, top.liubowen.proto.PlayerProto.PlayerMsg.Builder.class);
    }

    public static final int SIMPLE_PLAYER_FIELD_NUMBER = 1;
    private top.liubowen.proto.PlayerProto.SimplePlayerMsg simplePlayer_;
    /**
     * <pre>
     *  玩家基础信息
     * </pre>
     *
     * <code>.playerProto.SimplePlayerMsg simple_player = 1;</code>
     */
    public boolean hasSimplePlayer() {
      return simplePlayer_ != null;
    }
    /**
     * <pre>
     *  玩家基础信息
     * </pre>
     *
     * <code>.playerProto.SimplePlayerMsg simple_player = 1;</code>
     */
    public top.liubowen.proto.PlayerProto.SimplePlayerMsg getSimplePlayer() {
      return simplePlayer_ == null ? top.liubowen.proto.PlayerProto.SimplePlayerMsg.getDefaultInstance() : simplePlayer_;
    }
    /**
     * <pre>
     *  玩家基础信息
     * </pre>
     *
     * <code>.playerProto.SimplePlayerMsg simple_player = 1;</code>
     */
    public top.liubowen.proto.PlayerProto.SimplePlayerMsgOrBuilder getSimplePlayerOrBuilder() {
      return getSimplePlayer();
    }

    public static final int ROOM_CARD_NUM_FIELD_NUMBER = 2;
    private int roomCardNum_;
    /**
     * <pre>
     *  玩家房卡数量
     * </pre>
     *
     * <code>int32 room_card_num = 2;</code>
     */
    public int getRoomCardNum() {
      return roomCardNum_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (simplePlayer_ != null) {
        output.writeMessage(1, getSimplePlayer());
      }
      if (roomCardNum_ != 0) {
        output.writeInt32(2, roomCardNum_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (simplePlayer_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getSimplePlayer());
      }
      if (roomCardNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, roomCardNum_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof top.liubowen.proto.PlayerProto.PlayerMsg)) {
        return super.equals(obj);
      }
      top.liubowen.proto.PlayerProto.PlayerMsg other = (top.liubowen.proto.PlayerProto.PlayerMsg) obj;

      boolean result = true;
      result = result && (hasSimplePlayer() == other.hasSimplePlayer());
      if (hasSimplePlayer()) {
        result = result && getSimplePlayer()
            .equals(other.getSimplePlayer());
      }
      result = result && (getRoomCardNum()
          == other.getRoomCardNum());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSimplePlayer()) {
        hash = (37 * hash) + SIMPLE_PLAYER_FIELD_NUMBER;
        hash = (53 * hash) + getSimplePlayer().hashCode();
      }
      hash = (37 * hash) + ROOM_CARD_NUM_FIELD_NUMBER;
      hash = (53 * hash) + getRoomCardNum();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static top.liubowen.proto.PlayerProto.PlayerMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.liubowen.proto.PlayerProto.PlayerMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.liubowen.proto.PlayerProto.PlayerMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.liubowen.proto.PlayerProto.PlayerMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.liubowen.proto.PlayerProto.PlayerMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.liubowen.proto.PlayerProto.PlayerMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.liubowen.proto.PlayerProto.PlayerMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.liubowen.proto.PlayerProto.PlayerMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static top.liubowen.proto.PlayerProto.PlayerMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static top.liubowen.proto.PlayerProto.PlayerMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static top.liubowen.proto.PlayerProto.PlayerMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.liubowen.proto.PlayerProto.PlayerMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(top.liubowen.proto.PlayerProto.PlayerMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     ** 玩家信息 
     * </pre>
     *
     * Protobuf type {@code playerProto.PlayerMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:playerProto.PlayerMsg)
        top.liubowen.proto.PlayerProto.PlayerMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return top.liubowen.proto.PlayerProto.internal_static_playerProto_PlayerMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return top.liubowen.proto.PlayerProto.internal_static_playerProto_PlayerMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                top.liubowen.proto.PlayerProto.PlayerMsg.class, top.liubowen.proto.PlayerProto.PlayerMsg.Builder.class);
      }

      // Construct using top.liubowen.proto.PlayerProto.PlayerMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (simplePlayerBuilder_ == null) {
          simplePlayer_ = null;
        } else {
          simplePlayer_ = null;
          simplePlayerBuilder_ = null;
        }
        roomCardNum_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return top.liubowen.proto.PlayerProto.internal_static_playerProto_PlayerMsg_descriptor;
      }

      public top.liubowen.proto.PlayerProto.PlayerMsg getDefaultInstanceForType() {
        return top.liubowen.proto.PlayerProto.PlayerMsg.getDefaultInstance();
      }

      public top.liubowen.proto.PlayerProto.PlayerMsg build() {
        top.liubowen.proto.PlayerProto.PlayerMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public top.liubowen.proto.PlayerProto.PlayerMsg buildPartial() {
        top.liubowen.proto.PlayerProto.PlayerMsg result = new top.liubowen.proto.PlayerProto.PlayerMsg(this);
        if (simplePlayerBuilder_ == null) {
          result.simplePlayer_ = simplePlayer_;
        } else {
          result.simplePlayer_ = simplePlayerBuilder_.build();
        }
        result.roomCardNum_ = roomCardNum_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof top.liubowen.proto.PlayerProto.PlayerMsg) {
          return mergeFrom((top.liubowen.proto.PlayerProto.PlayerMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(top.liubowen.proto.PlayerProto.PlayerMsg other) {
        if (other == top.liubowen.proto.PlayerProto.PlayerMsg.getDefaultInstance()) return this;
        if (other.hasSimplePlayer()) {
          mergeSimplePlayer(other.getSimplePlayer());
        }
        if (other.getRoomCardNum() != 0) {
          setRoomCardNum(other.getRoomCardNum());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        top.liubowen.proto.PlayerProto.PlayerMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (top.liubowen.proto.PlayerProto.PlayerMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private top.liubowen.proto.PlayerProto.SimplePlayerMsg simplePlayer_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          top.liubowen.proto.PlayerProto.SimplePlayerMsg, top.liubowen.proto.PlayerProto.SimplePlayerMsg.Builder, top.liubowen.proto.PlayerProto.SimplePlayerMsgOrBuilder> simplePlayerBuilder_;
      /**
       * <pre>
       *  玩家基础信息
       * </pre>
       *
       * <code>.playerProto.SimplePlayerMsg simple_player = 1;</code>
       */
      public boolean hasSimplePlayer() {
        return simplePlayerBuilder_ != null || simplePlayer_ != null;
      }
      /**
       * <pre>
       *  玩家基础信息
       * </pre>
       *
       * <code>.playerProto.SimplePlayerMsg simple_player = 1;</code>
       */
      public top.liubowen.proto.PlayerProto.SimplePlayerMsg getSimplePlayer() {
        if (simplePlayerBuilder_ == null) {
          return simplePlayer_ == null ? top.liubowen.proto.PlayerProto.SimplePlayerMsg.getDefaultInstance() : simplePlayer_;
        } else {
          return simplePlayerBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *  玩家基础信息
       * </pre>
       *
       * <code>.playerProto.SimplePlayerMsg simple_player = 1;</code>
       */
      public Builder setSimplePlayer(top.liubowen.proto.PlayerProto.SimplePlayerMsg value) {
        if (simplePlayerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          simplePlayer_ = value;
          onChanged();
        } else {
          simplePlayerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *  玩家基础信息
       * </pre>
       *
       * <code>.playerProto.SimplePlayerMsg simple_player = 1;</code>
       */
      public Builder setSimplePlayer(
          top.liubowen.proto.PlayerProto.SimplePlayerMsg.Builder builderForValue) {
        if (simplePlayerBuilder_ == null) {
          simplePlayer_ = builderForValue.build();
          onChanged();
        } else {
          simplePlayerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *  玩家基础信息
       * </pre>
       *
       * <code>.playerProto.SimplePlayerMsg simple_player = 1;</code>
       */
      public Builder mergeSimplePlayer(top.liubowen.proto.PlayerProto.SimplePlayerMsg value) {
        if (simplePlayerBuilder_ == null) {
          if (simplePlayer_ != null) {
            simplePlayer_ =
              top.liubowen.proto.PlayerProto.SimplePlayerMsg.newBuilder(simplePlayer_).mergeFrom(value).buildPartial();
          } else {
            simplePlayer_ = value;
          }
          onChanged();
        } else {
          simplePlayerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *  玩家基础信息
       * </pre>
       *
       * <code>.playerProto.SimplePlayerMsg simple_player = 1;</code>
       */
      public Builder clearSimplePlayer() {
        if (simplePlayerBuilder_ == null) {
          simplePlayer_ = null;
          onChanged();
        } else {
          simplePlayer_ = null;
          simplePlayerBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *  玩家基础信息
       * </pre>
       *
       * <code>.playerProto.SimplePlayerMsg simple_player = 1;</code>
       */
      public top.liubowen.proto.PlayerProto.SimplePlayerMsg.Builder getSimplePlayerBuilder() {
        
        onChanged();
        return getSimplePlayerFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *  玩家基础信息
       * </pre>
       *
       * <code>.playerProto.SimplePlayerMsg simple_player = 1;</code>
       */
      public top.liubowen.proto.PlayerProto.SimplePlayerMsgOrBuilder getSimplePlayerOrBuilder() {
        if (simplePlayerBuilder_ != null) {
          return simplePlayerBuilder_.getMessageOrBuilder();
        } else {
          return simplePlayer_ == null ?
              top.liubowen.proto.PlayerProto.SimplePlayerMsg.getDefaultInstance() : simplePlayer_;
        }
      }
      /**
       * <pre>
       *  玩家基础信息
       * </pre>
       *
       * <code>.playerProto.SimplePlayerMsg simple_player = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          top.liubowen.proto.PlayerProto.SimplePlayerMsg, top.liubowen.proto.PlayerProto.SimplePlayerMsg.Builder, top.liubowen.proto.PlayerProto.SimplePlayerMsgOrBuilder> 
          getSimplePlayerFieldBuilder() {
        if (simplePlayerBuilder_ == null) {
          simplePlayerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              top.liubowen.proto.PlayerProto.SimplePlayerMsg, top.liubowen.proto.PlayerProto.SimplePlayerMsg.Builder, top.liubowen.proto.PlayerProto.SimplePlayerMsgOrBuilder>(
                  getSimplePlayer(),
                  getParentForChildren(),
                  isClean());
          simplePlayer_ = null;
        }
        return simplePlayerBuilder_;
      }

      private int roomCardNum_ ;
      /**
       * <pre>
       *  玩家房卡数量
       * </pre>
       *
       * <code>int32 room_card_num = 2;</code>
       */
      public int getRoomCardNum() {
        return roomCardNum_;
      }
      /**
       * <pre>
       *  玩家房卡数量
       * </pre>
       *
       * <code>int32 room_card_num = 2;</code>
       */
      public Builder setRoomCardNum(int value) {
        
        roomCardNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  玩家房卡数量
       * </pre>
       *
       * <code>int32 room_card_num = 2;</code>
       */
      public Builder clearRoomCardNum() {
        
        roomCardNum_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:playerProto.PlayerMsg)
    }

    // @@protoc_insertion_point(class_scope:playerProto.PlayerMsg)
    private static final top.liubowen.proto.PlayerProto.PlayerMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new top.liubowen.proto.PlayerProto.PlayerMsg();
    }

    public static top.liubowen.proto.PlayerProto.PlayerMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerMsg>
        PARSER = new com.google.protobuf.AbstractParser<PlayerMsg>() {
      public PlayerMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlayerMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerMsg> getParserForType() {
      return PARSER;
    }

    public top.liubowen.proto.PlayerProto.PlayerMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_playerProto_SimplePlayerMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_playerProto_SimplePlayerMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_playerProto_PlayerMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_playerProto_PlayerMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014player.proto\022\013playerProto\"s\n\017SimplePla" +
      "yerMsg\022\021\n\tplayer_id\030\001 \001(\003\022\020\n\010nickname\030\002 " +
      "\001(\t\022\022\n\nhead_image\030\003 \001(\t\022\'\n\005state\030\004 \001(\0162\030" +
      ".playerProto.PlayerState\"W\n\tPlayerMsg\0223\n" +
      "\rsimple_player\030\001 \001(\0132\034.playerProto.Simpl" +
      "ePlayerMsg\022\025\n\rroom_card_num\030\002 \001(\005*3\n\013Pla" +
      "yerState\022\n\n\006ONLINE\020\000\022\013\n\007OFFLINE\020\001\022\013\n\007IN_" +
      "GAME\020\002B!\n\022top.liubowen.protoB\013PlayerProt" +
      "ob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_playerProto_SimplePlayerMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_playerProto_SimplePlayerMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_playerProto_SimplePlayerMsg_descriptor,
        new java.lang.String[] { "PlayerId", "Nickname", "HeadImage", "State", });
    internal_static_playerProto_PlayerMsg_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_playerProto_PlayerMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_playerProto_PlayerMsg_descriptor,
        new java.lang.String[] { "SimplePlayer", "RoomCardNum", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
