// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: room.proto

package top.liubowen.proto;

public final class RoomProto {
  private RoomProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RoomMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:roomProto.RoomMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *  房间id
     * </pre>
     *
     * <code>int32 room_id = 1;</code>
     */
    int getRoomId();

    /**
     * <pre>
     *  房间玩家
     * </pre>
     *
     * <code>repeated .roomProto.RoomPlayer players = 2;</code>
     */
    java.util.List<top.liubowen.proto.RoomProto.RoomPlayer> 
        getPlayersList();
    /**
     * <pre>
     *  房间玩家
     * </pre>
     *
     * <code>repeated .roomProto.RoomPlayer players = 2;</code>
     */
    top.liubowen.proto.RoomProto.RoomPlayer getPlayers(int index);
    /**
     * <pre>
     *  房间玩家
     * </pre>
     *
     * <code>repeated .roomProto.RoomPlayer players = 2;</code>
     */
    int getPlayersCount();
    /**
     * <pre>
     *  房间玩家
     * </pre>
     *
     * <code>repeated .roomProto.RoomPlayer players = 2;</code>
     */
    java.util.List<? extends top.liubowen.proto.RoomProto.RoomPlayerOrBuilder> 
        getPlayersOrBuilderList();
    /**
     * <pre>
     *  房间玩家
     * </pre>
     *
     * <code>repeated .roomProto.RoomPlayer players = 2;</code>
     */
    top.liubowen.proto.RoomProto.RoomPlayerOrBuilder getPlayersOrBuilder(
        int index);

    /**
     * <pre>
     *  游戏类型
     * </pre>
     *
     * <code>.gameProto.GameType game_type = 3;</code>
     */
    int getGameTypeValue();
    /**
     * <pre>
     *  游戏类型
     * </pre>
     *
     * <code>.gameProto.GameType game_type = 3;</code>
     */
    top.liubowen.proto.GameProto.GameType getGameType();
  }
  /**
   * <pre>
   ** 房间消息 
   * </pre>
   *
   * Protobuf type {@code roomProto.RoomMsg}
   */
  public  static final class RoomMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:roomProto.RoomMsg)
      RoomMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RoomMsg.newBuilder() to construct.
    private RoomMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RoomMsg() {
      roomId_ = 0;
      players_ = java.util.Collections.emptyList();
      gameType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RoomMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              roomId_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                players_ = new java.util.ArrayList<top.liubowen.proto.RoomProto.RoomPlayer>();
                mutable_bitField0_ |= 0x00000002;
              }
              players_.add(
                  input.readMessage(top.liubowen.proto.RoomProto.RoomPlayer.parser(), extensionRegistry));
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              gameType_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          players_ = java.util.Collections.unmodifiableList(players_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return top.liubowen.proto.RoomProto.internal_static_roomProto_RoomMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return top.liubowen.proto.RoomProto.internal_static_roomProto_RoomMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              top.liubowen.proto.RoomProto.RoomMsg.class, top.liubowen.proto.RoomProto.RoomMsg.Builder.class);
    }

    private int bitField0_;
    public static final int ROOM_ID_FIELD_NUMBER = 1;
    private int roomId_;
    /**
     * <pre>
     *  房间id
     * </pre>
     *
     * <code>int32 room_id = 1;</code>
     */
    public int getRoomId() {
      return roomId_;
    }

    public static final int PLAYERS_FIELD_NUMBER = 2;
    private java.util.List<top.liubowen.proto.RoomProto.RoomPlayer> players_;
    /**
     * <pre>
     *  房间玩家
     * </pre>
     *
     * <code>repeated .roomProto.RoomPlayer players = 2;</code>
     */
    public java.util.List<top.liubowen.proto.RoomProto.RoomPlayer> getPlayersList() {
      return players_;
    }
    /**
     * <pre>
     *  房间玩家
     * </pre>
     *
     * <code>repeated .roomProto.RoomPlayer players = 2;</code>
     */
    public java.util.List<? extends top.liubowen.proto.RoomProto.RoomPlayerOrBuilder> 
        getPlayersOrBuilderList() {
      return players_;
    }
    /**
     * <pre>
     *  房间玩家
     * </pre>
     *
     * <code>repeated .roomProto.RoomPlayer players = 2;</code>
     */
    public int getPlayersCount() {
      return players_.size();
    }
    /**
     * <pre>
     *  房间玩家
     * </pre>
     *
     * <code>repeated .roomProto.RoomPlayer players = 2;</code>
     */
    public top.liubowen.proto.RoomProto.RoomPlayer getPlayers(int index) {
      return players_.get(index);
    }
    /**
     * <pre>
     *  房间玩家
     * </pre>
     *
     * <code>repeated .roomProto.RoomPlayer players = 2;</code>
     */
    public top.liubowen.proto.RoomProto.RoomPlayerOrBuilder getPlayersOrBuilder(
        int index) {
      return players_.get(index);
    }

    public static final int GAME_TYPE_FIELD_NUMBER = 3;
    private int gameType_;
    /**
     * <pre>
     *  游戏类型
     * </pre>
     *
     * <code>.gameProto.GameType game_type = 3;</code>
     */
    public int getGameTypeValue() {
      return gameType_;
    }
    /**
     * <pre>
     *  游戏类型
     * </pre>
     *
     * <code>.gameProto.GameType game_type = 3;</code>
     */
    public top.liubowen.proto.GameProto.GameType getGameType() {
      top.liubowen.proto.GameProto.GameType result = top.liubowen.proto.GameProto.GameType.valueOf(gameType_);
      return result == null ? top.liubowen.proto.GameProto.GameType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (roomId_ != 0) {
        output.writeInt32(1, roomId_);
      }
      for (int i = 0; i < players_.size(); i++) {
        output.writeMessage(2, players_.get(i));
      }
      if (gameType_ != top.liubowen.proto.GameProto.GameType.TUI_TONG_ZI.getNumber()) {
        output.writeEnum(3, gameType_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (roomId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, roomId_);
      }
      for (int i = 0; i < players_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, players_.get(i));
      }
      if (gameType_ != top.liubowen.proto.GameProto.GameType.TUI_TONG_ZI.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, gameType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof top.liubowen.proto.RoomProto.RoomMsg)) {
        return super.equals(obj);
      }
      top.liubowen.proto.RoomProto.RoomMsg other = (top.liubowen.proto.RoomProto.RoomMsg) obj;

      boolean result = true;
      result = result && (getRoomId()
          == other.getRoomId());
      result = result && getPlayersList()
          .equals(other.getPlayersList());
      result = result && gameType_ == other.gameType_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ROOM_ID_FIELD_NUMBER;
      hash = (53 * hash) + getRoomId();
      if (getPlayersCount() > 0) {
        hash = (37 * hash) + PLAYERS_FIELD_NUMBER;
        hash = (53 * hash) + getPlayersList().hashCode();
      }
      hash = (37 * hash) + GAME_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + gameType_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static top.liubowen.proto.RoomProto.RoomMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.liubowen.proto.RoomProto.RoomMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.liubowen.proto.RoomProto.RoomMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.liubowen.proto.RoomProto.RoomMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.liubowen.proto.RoomProto.RoomMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.liubowen.proto.RoomProto.RoomMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.liubowen.proto.RoomProto.RoomMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.liubowen.proto.RoomProto.RoomMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static top.liubowen.proto.RoomProto.RoomMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static top.liubowen.proto.RoomProto.RoomMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static top.liubowen.proto.RoomProto.RoomMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.liubowen.proto.RoomProto.RoomMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(top.liubowen.proto.RoomProto.RoomMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     ** 房间消息 
     * </pre>
     *
     * Protobuf type {@code roomProto.RoomMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:roomProto.RoomMsg)
        top.liubowen.proto.RoomProto.RoomMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return top.liubowen.proto.RoomProto.internal_static_roomProto_RoomMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return top.liubowen.proto.RoomProto.internal_static_roomProto_RoomMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                top.liubowen.proto.RoomProto.RoomMsg.class, top.liubowen.proto.RoomProto.RoomMsg.Builder.class);
      }

      // Construct using top.liubowen.proto.RoomProto.RoomMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPlayersFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        roomId_ = 0;

        if (playersBuilder_ == null) {
          players_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          playersBuilder_.clear();
        }
        gameType_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return top.liubowen.proto.RoomProto.internal_static_roomProto_RoomMsg_descriptor;
      }

      public top.liubowen.proto.RoomProto.RoomMsg getDefaultInstanceForType() {
        return top.liubowen.proto.RoomProto.RoomMsg.getDefaultInstance();
      }

      public top.liubowen.proto.RoomProto.RoomMsg build() {
        top.liubowen.proto.RoomProto.RoomMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public top.liubowen.proto.RoomProto.RoomMsg buildPartial() {
        top.liubowen.proto.RoomProto.RoomMsg result = new top.liubowen.proto.RoomProto.RoomMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.roomId_ = roomId_;
        if (playersBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            players_ = java.util.Collections.unmodifiableList(players_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.players_ = players_;
        } else {
          result.players_ = playersBuilder_.build();
        }
        result.gameType_ = gameType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof top.liubowen.proto.RoomProto.RoomMsg) {
          return mergeFrom((top.liubowen.proto.RoomProto.RoomMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(top.liubowen.proto.RoomProto.RoomMsg other) {
        if (other == top.liubowen.proto.RoomProto.RoomMsg.getDefaultInstance()) return this;
        if (other.getRoomId() != 0) {
          setRoomId(other.getRoomId());
        }
        if (playersBuilder_ == null) {
          if (!other.players_.isEmpty()) {
            if (players_.isEmpty()) {
              players_ = other.players_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensurePlayersIsMutable();
              players_.addAll(other.players_);
            }
            onChanged();
          }
        } else {
          if (!other.players_.isEmpty()) {
            if (playersBuilder_.isEmpty()) {
              playersBuilder_.dispose();
              playersBuilder_ = null;
              players_ = other.players_;
              bitField0_ = (bitField0_ & ~0x00000002);
              playersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPlayersFieldBuilder() : null;
            } else {
              playersBuilder_.addAllMessages(other.players_);
            }
          }
        }
        if (other.gameType_ != 0) {
          setGameTypeValue(other.getGameTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        top.liubowen.proto.RoomProto.RoomMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (top.liubowen.proto.RoomProto.RoomMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int roomId_ ;
      /**
       * <pre>
       *  房间id
       * </pre>
       *
       * <code>int32 room_id = 1;</code>
       */
      public int getRoomId() {
        return roomId_;
      }
      /**
       * <pre>
       *  房间id
       * </pre>
       *
       * <code>int32 room_id = 1;</code>
       */
      public Builder setRoomId(int value) {
        
        roomId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  房间id
       * </pre>
       *
       * <code>int32 room_id = 1;</code>
       */
      public Builder clearRoomId() {
        
        roomId_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<top.liubowen.proto.RoomProto.RoomPlayer> players_ =
        java.util.Collections.emptyList();
      private void ensurePlayersIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          players_ = new java.util.ArrayList<top.liubowen.proto.RoomProto.RoomPlayer>(players_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          top.liubowen.proto.RoomProto.RoomPlayer, top.liubowen.proto.RoomProto.RoomPlayer.Builder, top.liubowen.proto.RoomProto.RoomPlayerOrBuilder> playersBuilder_;

      /**
       * <pre>
       *  房间玩家
       * </pre>
       *
       * <code>repeated .roomProto.RoomPlayer players = 2;</code>
       */
      public java.util.List<top.liubowen.proto.RoomProto.RoomPlayer> getPlayersList() {
        if (playersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(players_);
        } else {
          return playersBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *  房间玩家
       * </pre>
       *
       * <code>repeated .roomProto.RoomPlayer players = 2;</code>
       */
      public int getPlayersCount() {
        if (playersBuilder_ == null) {
          return players_.size();
        } else {
          return playersBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *  房间玩家
       * </pre>
       *
       * <code>repeated .roomProto.RoomPlayer players = 2;</code>
       */
      public top.liubowen.proto.RoomProto.RoomPlayer getPlayers(int index) {
        if (playersBuilder_ == null) {
          return players_.get(index);
        } else {
          return playersBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *  房间玩家
       * </pre>
       *
       * <code>repeated .roomProto.RoomPlayer players = 2;</code>
       */
      public Builder setPlayers(
          int index, top.liubowen.proto.RoomProto.RoomPlayer value) {
        if (playersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlayersIsMutable();
          players_.set(index, value);
          onChanged();
        } else {
          playersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *  房间玩家
       * </pre>
       *
       * <code>repeated .roomProto.RoomPlayer players = 2;</code>
       */
      public Builder setPlayers(
          int index, top.liubowen.proto.RoomProto.RoomPlayer.Builder builderForValue) {
        if (playersBuilder_ == null) {
          ensurePlayersIsMutable();
          players_.set(index, builderForValue.build());
          onChanged();
        } else {
          playersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *  房间玩家
       * </pre>
       *
       * <code>repeated .roomProto.RoomPlayer players = 2;</code>
       */
      public Builder addPlayers(top.liubowen.proto.RoomProto.RoomPlayer value) {
        if (playersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlayersIsMutable();
          players_.add(value);
          onChanged();
        } else {
          playersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *  房间玩家
       * </pre>
       *
       * <code>repeated .roomProto.RoomPlayer players = 2;</code>
       */
      public Builder addPlayers(
          int index, top.liubowen.proto.RoomProto.RoomPlayer value) {
        if (playersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlayersIsMutable();
          players_.add(index, value);
          onChanged();
        } else {
          playersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *  房间玩家
       * </pre>
       *
       * <code>repeated .roomProto.RoomPlayer players = 2;</code>
       */
      public Builder addPlayers(
          top.liubowen.proto.RoomProto.RoomPlayer.Builder builderForValue) {
        if (playersBuilder_ == null) {
          ensurePlayersIsMutable();
          players_.add(builderForValue.build());
          onChanged();
        } else {
          playersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *  房间玩家
       * </pre>
       *
       * <code>repeated .roomProto.RoomPlayer players = 2;</code>
       */
      public Builder addPlayers(
          int index, top.liubowen.proto.RoomProto.RoomPlayer.Builder builderForValue) {
        if (playersBuilder_ == null) {
          ensurePlayersIsMutable();
          players_.add(index, builderForValue.build());
          onChanged();
        } else {
          playersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *  房间玩家
       * </pre>
       *
       * <code>repeated .roomProto.RoomPlayer players = 2;</code>
       */
      public Builder addAllPlayers(
          java.lang.Iterable<? extends top.liubowen.proto.RoomProto.RoomPlayer> values) {
        if (playersBuilder_ == null) {
          ensurePlayersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, players_);
          onChanged();
        } else {
          playersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *  房间玩家
       * </pre>
       *
       * <code>repeated .roomProto.RoomPlayer players = 2;</code>
       */
      public Builder clearPlayers() {
        if (playersBuilder_ == null) {
          players_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          playersBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *  房间玩家
       * </pre>
       *
       * <code>repeated .roomProto.RoomPlayer players = 2;</code>
       */
      public Builder removePlayers(int index) {
        if (playersBuilder_ == null) {
          ensurePlayersIsMutable();
          players_.remove(index);
          onChanged();
        } else {
          playersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *  房间玩家
       * </pre>
       *
       * <code>repeated .roomProto.RoomPlayer players = 2;</code>
       */
      public top.liubowen.proto.RoomProto.RoomPlayer.Builder getPlayersBuilder(
          int index) {
        return getPlayersFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *  房间玩家
       * </pre>
       *
       * <code>repeated .roomProto.RoomPlayer players = 2;</code>
       */
      public top.liubowen.proto.RoomProto.RoomPlayerOrBuilder getPlayersOrBuilder(
          int index) {
        if (playersBuilder_ == null) {
          return players_.get(index);  } else {
          return playersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *  房间玩家
       * </pre>
       *
       * <code>repeated .roomProto.RoomPlayer players = 2;</code>
       */
      public java.util.List<? extends top.liubowen.proto.RoomProto.RoomPlayerOrBuilder> 
           getPlayersOrBuilderList() {
        if (playersBuilder_ != null) {
          return playersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(players_);
        }
      }
      /**
       * <pre>
       *  房间玩家
       * </pre>
       *
       * <code>repeated .roomProto.RoomPlayer players = 2;</code>
       */
      public top.liubowen.proto.RoomProto.RoomPlayer.Builder addPlayersBuilder() {
        return getPlayersFieldBuilder().addBuilder(
            top.liubowen.proto.RoomProto.RoomPlayer.getDefaultInstance());
      }
      /**
       * <pre>
       *  房间玩家
       * </pre>
       *
       * <code>repeated .roomProto.RoomPlayer players = 2;</code>
       */
      public top.liubowen.proto.RoomProto.RoomPlayer.Builder addPlayersBuilder(
          int index) {
        return getPlayersFieldBuilder().addBuilder(
            index, top.liubowen.proto.RoomProto.RoomPlayer.getDefaultInstance());
      }
      /**
       * <pre>
       *  房间玩家
       * </pre>
       *
       * <code>repeated .roomProto.RoomPlayer players = 2;</code>
       */
      public java.util.List<top.liubowen.proto.RoomProto.RoomPlayer.Builder> 
           getPlayersBuilderList() {
        return getPlayersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          top.liubowen.proto.RoomProto.RoomPlayer, top.liubowen.proto.RoomProto.RoomPlayer.Builder, top.liubowen.proto.RoomProto.RoomPlayerOrBuilder> 
          getPlayersFieldBuilder() {
        if (playersBuilder_ == null) {
          playersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              top.liubowen.proto.RoomProto.RoomPlayer, top.liubowen.proto.RoomProto.RoomPlayer.Builder, top.liubowen.proto.RoomProto.RoomPlayerOrBuilder>(
                  players_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          players_ = null;
        }
        return playersBuilder_;
      }

      private int gameType_ = 0;
      /**
       * <pre>
       *  游戏类型
       * </pre>
       *
       * <code>.gameProto.GameType game_type = 3;</code>
       */
      public int getGameTypeValue() {
        return gameType_;
      }
      /**
       * <pre>
       *  游戏类型
       * </pre>
       *
       * <code>.gameProto.GameType game_type = 3;</code>
       */
      public Builder setGameTypeValue(int value) {
        gameType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  游戏类型
       * </pre>
       *
       * <code>.gameProto.GameType game_type = 3;</code>
       */
      public top.liubowen.proto.GameProto.GameType getGameType() {
        top.liubowen.proto.GameProto.GameType result = top.liubowen.proto.GameProto.GameType.valueOf(gameType_);
        return result == null ? top.liubowen.proto.GameProto.GameType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *  游戏类型
       * </pre>
       *
       * <code>.gameProto.GameType game_type = 3;</code>
       */
      public Builder setGameType(top.liubowen.proto.GameProto.GameType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        gameType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  游戏类型
       * </pre>
       *
       * <code>.gameProto.GameType game_type = 3;</code>
       */
      public Builder clearGameType() {
        
        gameType_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:roomProto.RoomMsg)
    }

    // @@protoc_insertion_point(class_scope:roomProto.RoomMsg)
    private static final top.liubowen.proto.RoomProto.RoomMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new top.liubowen.proto.RoomProto.RoomMsg();
    }

    public static top.liubowen.proto.RoomProto.RoomMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RoomMsg>
        PARSER = new com.google.protobuf.AbstractParser<RoomMsg>() {
      public RoomMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RoomMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RoomMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RoomMsg> getParserForType() {
      return PARSER;
    }

    public top.liubowen.proto.RoomProto.RoomMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RoomPlayerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:roomProto.RoomPlayer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *  玩家基础信息
     * </pre>
     *
     * <code>.playerProto.SimplePlayerMsg simple_player = 1;</code>
     */
    boolean hasSimplePlayer();
    /**
     * <pre>
     *  玩家基础信息
     * </pre>
     *
     * <code>.playerProto.SimplePlayerMsg simple_player = 1;</code>
     */
    top.liubowen.proto.PlayerProto.SimplePlayerMsg getSimplePlayer();
    /**
     * <pre>
     *  玩家基础信息
     * </pre>
     *
     * <code>.playerProto.SimplePlayerMsg simple_player = 1;</code>
     */
    top.liubowen.proto.PlayerProto.SimplePlayerMsgOrBuilder getSimplePlayerOrBuilder();
  }
  /**
   * <pre>
   ** 房间中玩家信息 
   * </pre>
   *
   * Protobuf type {@code roomProto.RoomPlayer}
   */
  public  static final class RoomPlayer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:roomProto.RoomPlayer)
      RoomPlayerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RoomPlayer.newBuilder() to construct.
    private RoomPlayer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RoomPlayer() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RoomPlayer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              top.liubowen.proto.PlayerProto.SimplePlayerMsg.Builder subBuilder = null;
              if (simplePlayer_ != null) {
                subBuilder = simplePlayer_.toBuilder();
              }
              simplePlayer_ = input.readMessage(top.liubowen.proto.PlayerProto.SimplePlayerMsg.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(simplePlayer_);
                simplePlayer_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return top.liubowen.proto.RoomProto.internal_static_roomProto_RoomPlayer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return top.liubowen.proto.RoomProto.internal_static_roomProto_RoomPlayer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              top.liubowen.proto.RoomProto.RoomPlayer.class, top.liubowen.proto.RoomProto.RoomPlayer.Builder.class);
    }

    public static final int SIMPLE_PLAYER_FIELD_NUMBER = 1;
    private top.liubowen.proto.PlayerProto.SimplePlayerMsg simplePlayer_;
    /**
     * <pre>
     *  玩家基础信息
     * </pre>
     *
     * <code>.playerProto.SimplePlayerMsg simple_player = 1;</code>
     */
    public boolean hasSimplePlayer() {
      return simplePlayer_ != null;
    }
    /**
     * <pre>
     *  玩家基础信息
     * </pre>
     *
     * <code>.playerProto.SimplePlayerMsg simple_player = 1;</code>
     */
    public top.liubowen.proto.PlayerProto.SimplePlayerMsg getSimplePlayer() {
      return simplePlayer_ == null ? top.liubowen.proto.PlayerProto.SimplePlayerMsg.getDefaultInstance() : simplePlayer_;
    }
    /**
     * <pre>
     *  玩家基础信息
     * </pre>
     *
     * <code>.playerProto.SimplePlayerMsg simple_player = 1;</code>
     */
    public top.liubowen.proto.PlayerProto.SimplePlayerMsgOrBuilder getSimplePlayerOrBuilder() {
      return getSimplePlayer();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (simplePlayer_ != null) {
        output.writeMessage(1, getSimplePlayer());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (simplePlayer_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getSimplePlayer());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof top.liubowen.proto.RoomProto.RoomPlayer)) {
        return super.equals(obj);
      }
      top.liubowen.proto.RoomProto.RoomPlayer other = (top.liubowen.proto.RoomProto.RoomPlayer) obj;

      boolean result = true;
      result = result && (hasSimplePlayer() == other.hasSimplePlayer());
      if (hasSimplePlayer()) {
        result = result && getSimplePlayer()
            .equals(other.getSimplePlayer());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSimplePlayer()) {
        hash = (37 * hash) + SIMPLE_PLAYER_FIELD_NUMBER;
        hash = (53 * hash) + getSimplePlayer().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static top.liubowen.proto.RoomProto.RoomPlayer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.liubowen.proto.RoomProto.RoomPlayer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.liubowen.proto.RoomProto.RoomPlayer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.liubowen.proto.RoomProto.RoomPlayer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.liubowen.proto.RoomProto.RoomPlayer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.liubowen.proto.RoomProto.RoomPlayer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.liubowen.proto.RoomProto.RoomPlayer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.liubowen.proto.RoomProto.RoomPlayer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static top.liubowen.proto.RoomProto.RoomPlayer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static top.liubowen.proto.RoomProto.RoomPlayer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static top.liubowen.proto.RoomProto.RoomPlayer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.liubowen.proto.RoomProto.RoomPlayer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(top.liubowen.proto.RoomProto.RoomPlayer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     ** 房间中玩家信息 
     * </pre>
     *
     * Protobuf type {@code roomProto.RoomPlayer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:roomProto.RoomPlayer)
        top.liubowen.proto.RoomProto.RoomPlayerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return top.liubowen.proto.RoomProto.internal_static_roomProto_RoomPlayer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return top.liubowen.proto.RoomProto.internal_static_roomProto_RoomPlayer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                top.liubowen.proto.RoomProto.RoomPlayer.class, top.liubowen.proto.RoomProto.RoomPlayer.Builder.class);
      }

      // Construct using top.liubowen.proto.RoomProto.RoomPlayer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (simplePlayerBuilder_ == null) {
          simplePlayer_ = null;
        } else {
          simplePlayer_ = null;
          simplePlayerBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return top.liubowen.proto.RoomProto.internal_static_roomProto_RoomPlayer_descriptor;
      }

      public top.liubowen.proto.RoomProto.RoomPlayer getDefaultInstanceForType() {
        return top.liubowen.proto.RoomProto.RoomPlayer.getDefaultInstance();
      }

      public top.liubowen.proto.RoomProto.RoomPlayer build() {
        top.liubowen.proto.RoomProto.RoomPlayer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public top.liubowen.proto.RoomProto.RoomPlayer buildPartial() {
        top.liubowen.proto.RoomProto.RoomPlayer result = new top.liubowen.proto.RoomProto.RoomPlayer(this);
        if (simplePlayerBuilder_ == null) {
          result.simplePlayer_ = simplePlayer_;
        } else {
          result.simplePlayer_ = simplePlayerBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof top.liubowen.proto.RoomProto.RoomPlayer) {
          return mergeFrom((top.liubowen.proto.RoomProto.RoomPlayer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(top.liubowen.proto.RoomProto.RoomPlayer other) {
        if (other == top.liubowen.proto.RoomProto.RoomPlayer.getDefaultInstance()) return this;
        if (other.hasSimplePlayer()) {
          mergeSimplePlayer(other.getSimplePlayer());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        top.liubowen.proto.RoomProto.RoomPlayer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (top.liubowen.proto.RoomProto.RoomPlayer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private top.liubowen.proto.PlayerProto.SimplePlayerMsg simplePlayer_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          top.liubowen.proto.PlayerProto.SimplePlayerMsg, top.liubowen.proto.PlayerProto.SimplePlayerMsg.Builder, top.liubowen.proto.PlayerProto.SimplePlayerMsgOrBuilder> simplePlayerBuilder_;
      /**
       * <pre>
       *  玩家基础信息
       * </pre>
       *
       * <code>.playerProto.SimplePlayerMsg simple_player = 1;</code>
       */
      public boolean hasSimplePlayer() {
        return simplePlayerBuilder_ != null || simplePlayer_ != null;
      }
      /**
       * <pre>
       *  玩家基础信息
       * </pre>
       *
       * <code>.playerProto.SimplePlayerMsg simple_player = 1;</code>
       */
      public top.liubowen.proto.PlayerProto.SimplePlayerMsg getSimplePlayer() {
        if (simplePlayerBuilder_ == null) {
          return simplePlayer_ == null ? top.liubowen.proto.PlayerProto.SimplePlayerMsg.getDefaultInstance() : simplePlayer_;
        } else {
          return simplePlayerBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *  玩家基础信息
       * </pre>
       *
       * <code>.playerProto.SimplePlayerMsg simple_player = 1;</code>
       */
      public Builder setSimplePlayer(top.liubowen.proto.PlayerProto.SimplePlayerMsg value) {
        if (simplePlayerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          simplePlayer_ = value;
          onChanged();
        } else {
          simplePlayerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *  玩家基础信息
       * </pre>
       *
       * <code>.playerProto.SimplePlayerMsg simple_player = 1;</code>
       */
      public Builder setSimplePlayer(
          top.liubowen.proto.PlayerProto.SimplePlayerMsg.Builder builderForValue) {
        if (simplePlayerBuilder_ == null) {
          simplePlayer_ = builderForValue.build();
          onChanged();
        } else {
          simplePlayerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *  玩家基础信息
       * </pre>
       *
       * <code>.playerProto.SimplePlayerMsg simple_player = 1;</code>
       */
      public Builder mergeSimplePlayer(top.liubowen.proto.PlayerProto.SimplePlayerMsg value) {
        if (simplePlayerBuilder_ == null) {
          if (simplePlayer_ != null) {
            simplePlayer_ =
              top.liubowen.proto.PlayerProto.SimplePlayerMsg.newBuilder(simplePlayer_).mergeFrom(value).buildPartial();
          } else {
            simplePlayer_ = value;
          }
          onChanged();
        } else {
          simplePlayerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *  玩家基础信息
       * </pre>
       *
       * <code>.playerProto.SimplePlayerMsg simple_player = 1;</code>
       */
      public Builder clearSimplePlayer() {
        if (simplePlayerBuilder_ == null) {
          simplePlayer_ = null;
          onChanged();
        } else {
          simplePlayer_ = null;
          simplePlayerBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *  玩家基础信息
       * </pre>
       *
       * <code>.playerProto.SimplePlayerMsg simple_player = 1;</code>
       */
      public top.liubowen.proto.PlayerProto.SimplePlayerMsg.Builder getSimplePlayerBuilder() {
        
        onChanged();
        return getSimplePlayerFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *  玩家基础信息
       * </pre>
       *
       * <code>.playerProto.SimplePlayerMsg simple_player = 1;</code>
       */
      public top.liubowen.proto.PlayerProto.SimplePlayerMsgOrBuilder getSimplePlayerOrBuilder() {
        if (simplePlayerBuilder_ != null) {
          return simplePlayerBuilder_.getMessageOrBuilder();
        } else {
          return simplePlayer_ == null ?
              top.liubowen.proto.PlayerProto.SimplePlayerMsg.getDefaultInstance() : simplePlayer_;
        }
      }
      /**
       * <pre>
       *  玩家基础信息
       * </pre>
       *
       * <code>.playerProto.SimplePlayerMsg simple_player = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          top.liubowen.proto.PlayerProto.SimplePlayerMsg, top.liubowen.proto.PlayerProto.SimplePlayerMsg.Builder, top.liubowen.proto.PlayerProto.SimplePlayerMsgOrBuilder> 
          getSimplePlayerFieldBuilder() {
        if (simplePlayerBuilder_ == null) {
          simplePlayerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              top.liubowen.proto.PlayerProto.SimplePlayerMsg, top.liubowen.proto.PlayerProto.SimplePlayerMsg.Builder, top.liubowen.proto.PlayerProto.SimplePlayerMsgOrBuilder>(
                  getSimplePlayer(),
                  getParentForChildren(),
                  isClean());
          simplePlayer_ = null;
        }
        return simplePlayerBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:roomProto.RoomPlayer)
    }

    // @@protoc_insertion_point(class_scope:roomProto.RoomPlayer)
    private static final top.liubowen.proto.RoomProto.RoomPlayer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new top.liubowen.proto.RoomProto.RoomPlayer();
    }

    public static top.liubowen.proto.RoomProto.RoomPlayer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RoomPlayer>
        PARSER = new com.google.protobuf.AbstractParser<RoomPlayer>() {
      public RoomPlayer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RoomPlayer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RoomPlayer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RoomPlayer> getParserForType() {
      return PARSER;
    }

    public top.liubowen.proto.RoomProto.RoomPlayer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_roomProto_RoomMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_roomProto_RoomMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_roomProto_RoomPlayer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_roomProto_RoomPlayer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nroom.proto\022\troomProto\032\014player.proto\032\ng" +
      "ame.proto\"j\n\007RoomMsg\022\017\n\007room_id\030\001 \001(\005\022&\n" +
      "\007players\030\002 \003(\0132\025.roomProto.RoomPlayer\022&\n" +
      "\tgame_type\030\003 \001(\0162\023.gameProto.GameType\"A\n" +
      "\nRoomPlayer\0223\n\rsimple_player\030\001 \001(\0132\034.pla" +
      "yerProto.SimplePlayerMsgB\037\n\022top.liubowen" +
      ".protoB\tRoomProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          top.liubowen.proto.PlayerProto.getDescriptor(),
          top.liubowen.proto.GameProto.getDescriptor(),
        }, assigner);
    internal_static_roomProto_RoomMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_roomProto_RoomMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_roomProto_RoomMsg_descriptor,
        new java.lang.String[] { "RoomId", "Players", "GameType", });
    internal_static_roomProto_RoomPlayer_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_roomProto_RoomPlayer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_roomProto_RoomPlayer_descriptor,
        new java.lang.String[] { "SimplePlayer", });
    top.liubowen.proto.PlayerProto.getDescriptor();
    top.liubowen.proto.GameProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
