// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package top.liubowen.proto;

public final class UserProto {
  private UserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code userProto.Gender}
   */
  public enum Gender
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *  女
     * </pre>
     *
     * <code>FEMALE = 0;</code>
     */
    FEMALE(0),
    /**
     * <pre>
     *  男
     * </pre>
     *
     * <code>MALE = 1;</code>
     */
    MALE(1),
    /**
     * <pre>
     * 未知
     * </pre>
     *
     * <code>UNKNOW = 3;</code>
     */
    UNKNOW(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *  女
     * </pre>
     *
     * <code>FEMALE = 0;</code>
     */
    public static final int FEMALE_VALUE = 0;
    /**
     * <pre>
     *  男
     * </pre>
     *
     * <code>MALE = 1;</code>
     */
    public static final int MALE_VALUE = 1;
    /**
     * <pre>
     * 未知
     * </pre>
     *
     * <code>UNKNOW = 3;</code>
     */
    public static final int UNKNOW_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Gender valueOf(int value) {
      return forNumber(value);
    }

    public static Gender forNumber(int value) {
      switch (value) {
        case 0: return FEMALE;
        case 1: return MALE;
        case 3: return UNKNOW;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Gender>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Gender> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Gender>() {
            public Gender findValueByNumber(int number) {
              return Gender.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return top.liubowen.proto.UserProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final Gender[] VALUES = values();

    public static Gender valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Gender(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:userProto.Gender)
  }

  public interface UserMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:userProto.UserMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *  用户id
     * </pre>
     *
     * <code>int64 user_id = 1;</code>
     */
    long getUserId();

    /**
     * <pre>
     *  用户名称
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <pre>
     *  用户名称
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     *  用户头像
     * </pre>
     *
     * <code>string head_image = 3;</code>
     */
    java.lang.String getHeadImage();
    /**
     * <pre>
     *  用户头像
     * </pre>
     *
     * <code>string head_image = 3;</code>
     */
    com.google.protobuf.ByteString
        getHeadImageBytes();

    /**
     * <pre>
     *  用户性别
     * </pre>
     *
     * <code>.userProto.Gender gender = 4;</code>
     */
    int getGenderValue();
    /**
     * <pre>
     *  用户性别
     * </pre>
     *
     * <code>.userProto.Gender gender = 4;</code>
     */
    top.liubowen.proto.UserProto.Gender getGender();
  }
  /**
   * <pre>
   ** 用户信息 
   * </pre>
   *
   * Protobuf type {@code userProto.UserMsg}
   */
  public  static final class UserMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:userProto.UserMsg)
      UserMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserMsg.newBuilder() to construct.
    private UserMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserMsg() {
      userId_ = 0L;
      name_ = "";
      headImage_ = "";
      gender_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              userId_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              headImage_ = s;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              gender_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return top.liubowen.proto.UserProto.internal_static_userProto_UserMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return top.liubowen.proto.UserProto.internal_static_userProto_UserMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              top.liubowen.proto.UserProto.UserMsg.class, top.liubowen.proto.UserProto.UserMsg.Builder.class);
    }

    public static final int USER_ID_FIELD_NUMBER = 1;
    private long userId_;
    /**
     * <pre>
     *  用户id
     * </pre>
     *
     * <code>int64 user_id = 1;</code>
     */
    public long getUserId() {
      return userId_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     *  用户名称
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *  用户名称
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HEAD_IMAGE_FIELD_NUMBER = 3;
    private volatile java.lang.Object headImage_;
    /**
     * <pre>
     *  用户头像
     * </pre>
     *
     * <code>string head_image = 3;</code>
     */
    public java.lang.String getHeadImage() {
      java.lang.Object ref = headImage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        headImage_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *  用户头像
     * </pre>
     *
     * <code>string head_image = 3;</code>
     */
    public com.google.protobuf.ByteString
        getHeadImageBytes() {
      java.lang.Object ref = headImage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        headImage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GENDER_FIELD_NUMBER = 4;
    private int gender_;
    /**
     * <pre>
     *  用户性别
     * </pre>
     *
     * <code>.userProto.Gender gender = 4;</code>
     */
    public int getGenderValue() {
      return gender_;
    }
    /**
     * <pre>
     *  用户性别
     * </pre>
     *
     * <code>.userProto.Gender gender = 4;</code>
     */
    public top.liubowen.proto.UserProto.Gender getGender() {
      top.liubowen.proto.UserProto.Gender result = top.liubowen.proto.UserProto.Gender.valueOf(gender_);
      return result == null ? top.liubowen.proto.UserProto.Gender.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0L) {
        output.writeInt64(1, userId_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!getHeadImageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, headImage_);
      }
      if (gender_ != top.liubowen.proto.UserProto.Gender.FEMALE.getNumber()) {
        output.writeEnum(4, gender_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, userId_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!getHeadImageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, headImage_);
      }
      if (gender_ != top.liubowen.proto.UserProto.Gender.FEMALE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, gender_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof top.liubowen.proto.UserProto.UserMsg)) {
        return super.equals(obj);
      }
      top.liubowen.proto.UserProto.UserMsg other = (top.liubowen.proto.UserProto.UserMsg) obj;

      boolean result = true;
      result = result && (getUserId()
          == other.getUserId());
      result = result && getName()
          .equals(other.getName());
      result = result && getHeadImage()
          .equals(other.getHeadImage());
      result = result && gender_ == other.gender_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + HEAD_IMAGE_FIELD_NUMBER;
      hash = (53 * hash) + getHeadImage().hashCode();
      hash = (37 * hash) + GENDER_FIELD_NUMBER;
      hash = (53 * hash) + gender_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static top.liubowen.proto.UserProto.UserMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.liubowen.proto.UserProto.UserMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.liubowen.proto.UserProto.UserMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.liubowen.proto.UserProto.UserMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.liubowen.proto.UserProto.UserMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.liubowen.proto.UserProto.UserMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.liubowen.proto.UserProto.UserMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.liubowen.proto.UserProto.UserMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static top.liubowen.proto.UserProto.UserMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static top.liubowen.proto.UserProto.UserMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static top.liubowen.proto.UserProto.UserMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.liubowen.proto.UserProto.UserMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(top.liubowen.proto.UserProto.UserMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     ** 用户信息 
     * </pre>
     *
     * Protobuf type {@code userProto.UserMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:userProto.UserMsg)
        top.liubowen.proto.UserProto.UserMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return top.liubowen.proto.UserProto.internal_static_userProto_UserMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return top.liubowen.proto.UserProto.internal_static_userProto_UserMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                top.liubowen.proto.UserProto.UserMsg.class, top.liubowen.proto.UserProto.UserMsg.Builder.class);
      }

      // Construct using top.liubowen.proto.UserProto.UserMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userId_ = 0L;

        name_ = "";

        headImage_ = "";

        gender_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return top.liubowen.proto.UserProto.internal_static_userProto_UserMsg_descriptor;
      }

      public top.liubowen.proto.UserProto.UserMsg getDefaultInstanceForType() {
        return top.liubowen.proto.UserProto.UserMsg.getDefaultInstance();
      }

      public top.liubowen.proto.UserProto.UserMsg build() {
        top.liubowen.proto.UserProto.UserMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public top.liubowen.proto.UserProto.UserMsg buildPartial() {
        top.liubowen.proto.UserProto.UserMsg result = new top.liubowen.proto.UserProto.UserMsg(this);
        result.userId_ = userId_;
        result.name_ = name_;
        result.headImage_ = headImage_;
        result.gender_ = gender_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof top.liubowen.proto.UserProto.UserMsg) {
          return mergeFrom((top.liubowen.proto.UserProto.UserMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(top.liubowen.proto.UserProto.UserMsg other) {
        if (other == top.liubowen.proto.UserProto.UserMsg.getDefaultInstance()) return this;
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getHeadImage().isEmpty()) {
          headImage_ = other.headImage_;
          onChanged();
        }
        if (other.gender_ != 0) {
          setGenderValue(other.getGenderValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        top.liubowen.proto.UserProto.UserMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (top.liubowen.proto.UserProto.UserMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long userId_ ;
      /**
       * <pre>
       *  用户id
       * </pre>
       *
       * <code>int64 user_id = 1;</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <pre>
       *  用户id
       * </pre>
       *
       * <code>int64 user_id = 1;</code>
       */
      public Builder setUserId(long value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  用户id
       * </pre>
       *
       * <code>int64 user_id = 1;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       *  用户名称
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *  用户名称
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *  用户名称
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  用户名称
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  用户名称
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object headImage_ = "";
      /**
       * <pre>
       *  用户头像
       * </pre>
       *
       * <code>string head_image = 3;</code>
       */
      public java.lang.String getHeadImage() {
        java.lang.Object ref = headImage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          headImage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *  用户头像
       * </pre>
       *
       * <code>string head_image = 3;</code>
       */
      public com.google.protobuf.ByteString
          getHeadImageBytes() {
        java.lang.Object ref = headImage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          headImage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *  用户头像
       * </pre>
       *
       * <code>string head_image = 3;</code>
       */
      public Builder setHeadImage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        headImage_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  用户头像
       * </pre>
       *
       * <code>string head_image = 3;</code>
       */
      public Builder clearHeadImage() {
        
        headImage_ = getDefaultInstance().getHeadImage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  用户头像
       * </pre>
       *
       * <code>string head_image = 3;</code>
       */
      public Builder setHeadImageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        headImage_ = value;
        onChanged();
        return this;
      }

      private int gender_ = 0;
      /**
       * <pre>
       *  用户性别
       * </pre>
       *
       * <code>.userProto.Gender gender = 4;</code>
       */
      public int getGenderValue() {
        return gender_;
      }
      /**
       * <pre>
       *  用户性别
       * </pre>
       *
       * <code>.userProto.Gender gender = 4;</code>
       */
      public Builder setGenderValue(int value) {
        gender_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  用户性别
       * </pre>
       *
       * <code>.userProto.Gender gender = 4;</code>
       */
      public top.liubowen.proto.UserProto.Gender getGender() {
        top.liubowen.proto.UserProto.Gender result = top.liubowen.proto.UserProto.Gender.valueOf(gender_);
        return result == null ? top.liubowen.proto.UserProto.Gender.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *  用户性别
       * </pre>
       *
       * <code>.userProto.Gender gender = 4;</code>
       */
      public Builder setGender(top.liubowen.proto.UserProto.Gender value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        gender_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  用户性别
       * </pre>
       *
       * <code>.userProto.Gender gender = 4;</code>
       */
      public Builder clearGender() {
        
        gender_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:userProto.UserMsg)
    }

    // @@protoc_insertion_point(class_scope:userProto.UserMsg)
    private static final top.liubowen.proto.UserProto.UserMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new top.liubowen.proto.UserProto.UserMsg();
    }

    public static top.liubowen.proto.UserProto.UserMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserMsg>
        PARSER = new com.google.protobuf.AbstractParser<UserMsg>() {
      public UserMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserMsg> getParserForType() {
      return PARSER;
    }

    public top.liubowen.proto.UserProto.UserMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_userProto_UserMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_userProto_UserMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022\tuserProto\"_\n\007UserMsg\022\017\n\007us" +
      "er_id\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022\022\n\nhead_image\030" +
      "\003 \001(\t\022!\n\006gender\030\004 \001(\0162\021.userProto.Gender" +
      "**\n\006Gender\022\n\n\006FEMALE\020\000\022\010\n\004MALE\020\001\022\n\n\006UNKN" +
      "OW\020\003B\037\n\022top.liubowen.protoB\tUserProtob\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_userProto_UserMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_userProto_UserMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_userProto_UserMsg_descriptor,
        new java.lang.String[] { "UserId", "Name", "HeadImage", "Gender", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
